export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";

export const USER_GETALL_REQUEST = "USER_GETALL_REQUEST";
export const USER_GETALL_SUCCESS = "USER_GETALL_SUCCESS";
export const USER_GETALL_FAIL = "USER_GETALL_FAIL";
